/*
 * Reffueld API
 * **Reffueld's API** 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.reffueld.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.reffueld.client.model.Geojson;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * CouponTypeUpdateRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T18:05:40.872Z")
public class CouponTypeUpdateRequest {
  @SerializedName("name")
  private String name = null;

  @SerializedName("tags")
  private List<String> tags = new ArrayList<String>();

  @SerializedName("description")
  private String description = null;

  @SerializedName("expiry")
  private DateTime expiry = null;

  @SerializedName("value")
  private Integer value = null;

  @SerializedName("reciprocal_value")
  private Integer reciprocalValue = null;

  @SerializedName("fences")
  private Geojson fences = null;

  public CouponTypeUpdateRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CouponTypeUpdateRequest tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public CouponTypeUpdateRequest addTagsItem(String tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public CouponTypeUpdateRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CouponTypeUpdateRequest expiry(DateTime expiry) {
    this.expiry = expiry;
    return this;
  }

   /**
   * Get expiry
   * @return expiry
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getExpiry() {
    return expiry;
  }

  public void setExpiry(DateTime expiry) {
    this.expiry = expiry;
  }

  public CouponTypeUpdateRequest value(Integer value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * minimum: 0
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getValue() {
    return value;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public CouponTypeUpdateRequest reciprocalValue(Integer reciprocalValue) {
    this.reciprocalValue = reciprocalValue;
    return this;
  }

   /**
   * Get reciprocalValue
   * minimum: 0
   * @return reciprocalValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getReciprocalValue() {
    return reciprocalValue;
  }

  public void setReciprocalValue(Integer reciprocalValue) {
    this.reciprocalValue = reciprocalValue;
  }

  public CouponTypeUpdateRequest fences(Geojson fences) {
    this.fences = fences;
    return this;
  }

   /**
   * Get fences
   * @return fences
  **/
  @ApiModelProperty(example = "null", value = "")
  public Geojson getFences() {
    return fences;
  }

  public void setFences(Geojson fences) {
    this.fences = fences;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponTypeUpdateRequest couponTypeUpdateRequest = (CouponTypeUpdateRequest) o;
    return Objects.equals(this.name, couponTypeUpdateRequest.name) &&
        Objects.equals(this.tags, couponTypeUpdateRequest.tags) &&
        Objects.equals(this.description, couponTypeUpdateRequest.description) &&
        Objects.equals(this.expiry, couponTypeUpdateRequest.expiry) &&
        Objects.equals(this.value, couponTypeUpdateRequest.value) &&
        Objects.equals(this.reciprocalValue, couponTypeUpdateRequest.reciprocalValue) &&
        Objects.equals(this.fences, couponTypeUpdateRequest.fences);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, tags, description, expiry, value, reciprocalValue, fences);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponTypeUpdateRequest {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    expiry: ").append(toIndentedString(expiry)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    reciprocalValue: ").append(toIndentedString(reciprocalValue)).append("\n");
    sb.append("    fences: ").append(toIndentedString(fences)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

