/*
 * Reffueld API
 * **Reffueld's API** 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.reffueld.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.reffueld.client.model.Geojson;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * CoupontTypeCreateRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T18:05:40.872Z")
public class CoupontTypeCreateRequest {
  @SerializedName("name")
  private String name = null;

  @SerializedName("value")
  private Integer value = null;

  @SerializedName("from_role")
  private String fromRole = null;

  @SerializedName("to_role")
  private String toRole = null;

  @SerializedName("expiry")
  private DateTime expiry = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("tags")
  private List<String> tags = new ArrayList<String>();

  @SerializedName("reciprocal_value")
  private Integer reciprocalValue = null;

  /**
   * Gets or Sets codeType
   */
  public enum CodeTypeEnum {
    @SerializedName("RANDOM")
    RANDOM("RANDOM"),
    
    @SerializedName("SEQUENTIAL")
    SEQUENTIAL("SEQUENTIAL");

    private String value;

    CodeTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("code_type")
  private CodeTypeEnum codeType = CodeTypeEnum.RANDOM;

  @SerializedName("code_prefix")
  private String codePrefix = null;

  @SerializedName("claim_limit")
  private Integer claimLimit = null;

  /**
   * Gets or Sets applicability
   */
  public enum ApplicabilityEnum {
    @SerializedName("ANY")
    ANY("ANY"),
    
    @SerializedName("NEW_USER_ONLY")
    NEW_USER_ONLY("NEW_USER_ONLY");

    private String value;

    ApplicabilityEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("applicability")
  private ApplicabilityEnum applicability = ApplicabilityEnum.ANY;

  @SerializedName("fences")
  private Geojson fences = null;

  public CoupontTypeCreateRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CoupontTypeCreateRequest value(Integer value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * minimum: 0
   * @return value
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getValue() {
    return value;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public CoupontTypeCreateRequest fromRole(String fromRole) {
    this.fromRole = fromRole;
    return this;
  }

   /**
   * Valid values are in settings
   * @return fromRole
  **/
  @ApiModelProperty(example = "null", required = true, value = "Valid values are in settings")
  public String getFromRole() {
    return fromRole;
  }

  public void setFromRole(String fromRole) {
    this.fromRole = fromRole;
  }

  public CoupontTypeCreateRequest toRole(String toRole) {
    this.toRole = toRole;
    return this;
  }

   /**
   * Valid values are in settings
   * @return toRole
  **/
  @ApiModelProperty(example = "null", required = true, value = "Valid values are in settings")
  public String getToRole() {
    return toRole;
  }

  public void setToRole(String toRole) {
    this.toRole = toRole;
  }

  public CoupontTypeCreateRequest expiry(DateTime expiry) {
    this.expiry = expiry;
    return this;
  }

   /**
   * Get expiry
   * @return expiry
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getExpiry() {
    return expiry;
  }

  public void setExpiry(DateTime expiry) {
    this.expiry = expiry;
  }

  public CoupontTypeCreateRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CoupontTypeCreateRequest tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public CoupontTypeCreateRequest addTagsItem(String tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public CoupontTypeCreateRequest reciprocalValue(Integer reciprocalValue) {
    this.reciprocalValue = reciprocalValue;
    return this;
  }

   /**
   * Get reciprocalValue
   * minimum: 0
   * @return reciprocalValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getReciprocalValue() {
    return reciprocalValue;
  }

  public void setReciprocalValue(Integer reciprocalValue) {
    this.reciprocalValue = reciprocalValue;
  }

  public CoupontTypeCreateRequest codeType(CodeTypeEnum codeType) {
    this.codeType = codeType;
    return this;
  }

   /**
   * Get codeType
   * @return codeType
  **/
  @ApiModelProperty(example = "null", value = "")
  public CodeTypeEnum getCodeType() {
    return codeType;
  }

  public void setCodeType(CodeTypeEnum codeType) {
    this.codeType = codeType;
  }

  public CoupontTypeCreateRequest codePrefix(String codePrefix) {
    this.codePrefix = codePrefix;
    return this;
  }

   /**
   * Get codePrefix
   * @return codePrefix
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCodePrefix() {
    return codePrefix;
  }

  public void setCodePrefix(String codePrefix) {
    this.codePrefix = codePrefix;
  }

  public CoupontTypeCreateRequest claimLimit(Integer claimLimit) {
    this.claimLimit = claimLimit;
    return this;
  }

   /**
   * Get claimLimit
   * minimum: 0
   * @return claimLimit
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getClaimLimit() {
    return claimLimit;
  }

  public void setClaimLimit(Integer claimLimit) {
    this.claimLimit = claimLimit;
  }

  public CoupontTypeCreateRequest applicability(ApplicabilityEnum applicability) {
    this.applicability = applicability;
    return this;
  }

   /**
   * Get applicability
   * @return applicability
  **/
  @ApiModelProperty(example = "null", value = "")
  public ApplicabilityEnum getApplicability() {
    return applicability;
  }

  public void setApplicability(ApplicabilityEnum applicability) {
    this.applicability = applicability;
  }

  public CoupontTypeCreateRequest fences(Geojson fences) {
    this.fences = fences;
    return this;
  }

   /**
   * Get fences
   * @return fences
  **/
  @ApiModelProperty(example = "null", value = "")
  public Geojson getFences() {
    return fences;
  }

  public void setFences(Geojson fences) {
    this.fences = fences;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CoupontTypeCreateRequest coupontTypeCreateRequest = (CoupontTypeCreateRequest) o;
    return Objects.equals(this.name, coupontTypeCreateRequest.name) &&
        Objects.equals(this.value, coupontTypeCreateRequest.value) &&
        Objects.equals(this.fromRole, coupontTypeCreateRequest.fromRole) &&
        Objects.equals(this.toRole, coupontTypeCreateRequest.toRole) &&
        Objects.equals(this.expiry, coupontTypeCreateRequest.expiry) &&
        Objects.equals(this.description, coupontTypeCreateRequest.description) &&
        Objects.equals(this.tags, coupontTypeCreateRequest.tags) &&
        Objects.equals(this.reciprocalValue, coupontTypeCreateRequest.reciprocalValue) &&
        Objects.equals(this.codeType, coupontTypeCreateRequest.codeType) &&
        Objects.equals(this.codePrefix, coupontTypeCreateRequest.codePrefix) &&
        Objects.equals(this.claimLimit, coupontTypeCreateRequest.claimLimit) &&
        Objects.equals(this.applicability, coupontTypeCreateRequest.applicability) &&
        Objects.equals(this.fences, coupontTypeCreateRequest.fences);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, value, fromRole, toRole, expiry, description, tags, reciprocalValue, codeType, codePrefix, claimLimit, applicability, fences);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CoupontTypeCreateRequest {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    fromRole: ").append(toIndentedString(fromRole)).append("\n");
    sb.append("    toRole: ").append(toIndentedString(toRole)).append("\n");
    sb.append("    expiry: ").append(toIndentedString(expiry)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    reciprocalValue: ").append(toIndentedString(reciprocalValue)).append("\n");
    sb.append("    codeType: ").append(toIndentedString(codeType)).append("\n");
    sb.append("    codePrefix: ").append(toIndentedString(codePrefix)).append("\n");
    sb.append("    claimLimit: ").append(toIndentedString(claimLimit)).append("\n");
    sb.append("    applicability: ").append(toIndentedString(applicability)).append("\n");
    sb.append("    fences: ").append(toIndentedString(fences)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

