/*
 * Reffueld API
 * **Reffueld's API** 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.reffueld.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.reffueld.client.model.CouponTypeResponse;
import com.reffueld.client.model.MetaList;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * CouponTypeListResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T18:05:40.872Z")
public class CouponTypeListResponse {
  @SerializedName("_meta")
  private MetaList meta = null;

  @SerializedName("data")
  private List<CouponTypeResponse> data = new ArrayList<CouponTypeResponse>();

  public CouponTypeListResponse meta(MetaList meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @ApiModelProperty(example = "null", value = "")
  public MetaList getMeta() {
    return meta;
  }

  public void setMeta(MetaList meta) {
    this.meta = meta;
  }

  public CouponTypeListResponse data(List<CouponTypeResponse> data) {
    this.data = data;
    return this;
  }

  public CouponTypeListResponse addDataItem(CouponTypeResponse dataItem) {
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<CouponTypeResponse> getData() {
    return data;
  }

  public void setData(List<CouponTypeResponse> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponTypeListResponse couponTypeListResponse = (CouponTypeListResponse) o;
    return Objects.equals(this.meta, couponTypeListResponse.meta) &&
        Objects.equals(this.data, couponTypeListResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponTypeListResponse {\n");
    
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

