/*
 * Reffueld API
 * **Reffueld's API** 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.reffueld.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.reffueld.client.model.CouponTypeResponse;
import com.reffueld.client.model.CouponUserResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * CouponResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T18:05:40.872Z")
public class CouponResponse {
  @SerializedName("id")
  private String id = null;

  @SerializedName("created")
  private DateTime created = null;

  @SerializedName("cancelled")
  private DateTime cancelled = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("value")
  private Integer value = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("type")
  private CouponTypeResponse type = null;

  @SerializedName("from_user")
  private CouponUserResponse fromUser = null;

  @SerializedName("to_user")
  private CouponUserResponse toUser = null;

  @SerializedName("claimed_count")
  private Integer claimedCount = null;

  public CouponResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * unique
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "unique")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CouponResponse created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public CouponResponse cancelled(DateTime cancelled) {
    this.cancelled = cancelled;
    return this;
  }

   /**
   * Get cancelled
   * @return cancelled
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCancelled() {
    return cancelled;
  }

  public void setCancelled(DateTime cancelled) {
    this.cancelled = cancelled;
  }

  public CouponResponse code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public CouponResponse value(Integer value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getValue() {
    return value;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public CouponResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CouponResponse type(CouponTypeResponse type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public CouponTypeResponse getType() {
    return type;
  }

  public void setType(CouponTypeResponse type) {
    this.type = type;
  }

  public CouponResponse fromUser(CouponUserResponse fromUser) {
    this.fromUser = fromUser;
    return this;
  }

   /**
   * Get fromUser
   * @return fromUser
  **/
  @ApiModelProperty(example = "null", value = "")
  public CouponUserResponse getFromUser() {
    return fromUser;
  }

  public void setFromUser(CouponUserResponse fromUser) {
    this.fromUser = fromUser;
  }

  public CouponResponse toUser(CouponUserResponse toUser) {
    this.toUser = toUser;
    return this;
  }

   /**
   * Get toUser
   * @return toUser
  **/
  @ApiModelProperty(example = "null", value = "")
  public CouponUserResponse getToUser() {
    return toUser;
  }

  public void setToUser(CouponUserResponse toUser) {
    this.toUser = toUser;
  }

  public CouponResponse claimedCount(Integer claimedCount) {
    this.claimedCount = claimedCount;
    return this;
  }

   /**
   * Get claimedCount
   * @return claimedCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getClaimedCount() {
    return claimedCount;
  }

  public void setClaimedCount(Integer claimedCount) {
    this.claimedCount = claimedCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponResponse couponResponse = (CouponResponse) o;
    return Objects.equals(this.id, couponResponse.id) &&
        Objects.equals(this.created, couponResponse.created) &&
        Objects.equals(this.cancelled, couponResponse.cancelled) &&
        Objects.equals(this.code, couponResponse.code) &&
        Objects.equals(this.value, couponResponse.value) &&
        Objects.equals(this.description, couponResponse.description) &&
        Objects.equals(this.type, couponResponse.type) &&
        Objects.equals(this.fromUser, couponResponse.fromUser) &&
        Objects.equals(this.toUser, couponResponse.toUser) &&
        Objects.equals(this.claimedCount, couponResponse.claimedCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, created, cancelled, code, value, description, type, fromUser, toUser, claimedCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    cancelled: ").append(toIndentedString(cancelled)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    fromUser: ").append(toIndentedString(fromUser)).append("\n");
    sb.append("    toUser: ").append(toIndentedString(toUser)).append("\n");
    sb.append("    claimedCount: ").append(toIndentedString(claimedCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

