/*
 * Reffueld API
 * **Reffueld's API** 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.reffueld.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.reffueld.client.model.CouponResponse;
import com.reffueld.client.model.CouponUserResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * CouponTransactionResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T18:05:40.872Z")
public class CouponTransactionResponse {
  @SerializedName("id")
  private String id = null;

  @SerializedName("created")
  private DateTime created = null;

  @SerializedName("amount")
  private Integer amount = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    @SerializedName("CHARGE")
    CHARGE("CHARGE"),
    
    @SerializedName("REFUND")
    REFUND("REFUND"),
    
    @SerializedName("INCREASE_BALANCE")
    INCREASE_BALANCE("INCREASE_BALANCE"),
    
    @SerializedName("DECREASE_BALANCE")
    DECREASE_BALANCE("DECREASE_BALANCE"),
    
    @SerializedName("EXPIRE_BALANCE")
    EXPIRE_BALANCE("EXPIRE_BALANCE"),
    
    @SerializedName("RECIPROCITY")
    RECIPROCITY("RECIPROCITY"),
    
    @SerializedName("CLAIM")
    CLAIM("CLAIM");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("user")
  private CouponUserResponse user = null;

  @SerializedName("coupon")
  private CouponResponse coupon = null;

  public CouponTransactionResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * unique
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "unique")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CouponTransactionResponse created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public CouponTransactionResponse amount(Integer amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getAmount() {
    return amount;
  }

  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  public CouponTransactionResponse type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public CouponTransactionResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CouponTransactionResponse user(CouponUserResponse user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(example = "null", value = "")
  public CouponUserResponse getUser() {
    return user;
  }

  public void setUser(CouponUserResponse user) {
    this.user = user;
  }

  public CouponTransactionResponse coupon(CouponResponse coupon) {
    this.coupon = coupon;
    return this;
  }

   /**
   * Get coupon
   * @return coupon
  **/
  @ApiModelProperty(example = "null", value = "")
  public CouponResponse getCoupon() {
    return coupon;
  }

  public void setCoupon(CouponResponse coupon) {
    this.coupon = coupon;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponTransactionResponse couponTransactionResponse = (CouponTransactionResponse) o;
    return Objects.equals(this.id, couponTransactionResponse.id) &&
        Objects.equals(this.created, couponTransactionResponse.created) &&
        Objects.equals(this.amount, couponTransactionResponse.amount) &&
        Objects.equals(this.type, couponTransactionResponse.type) &&
        Objects.equals(this.description, couponTransactionResponse.description) &&
        Objects.equals(this.user, couponTransactionResponse.user) &&
        Objects.equals(this.coupon, couponTransactionResponse.coupon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, created, amount, type, description, user, coupon);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponTransactionResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    coupon: ").append(toIndentedString(coupon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

