/*
 * Reffueld API
 * **Reffueld's API**
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.reffueld.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CouponUserTransactionRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T18:05:40.872Z")
public class CouponUserTransactionRequest {

  public static final String CHARGE = "charge";
  public static final String REFUND = "refund";
  public static final String INCREASE = "increase";
  public static final String DECREASE = "decrease";
  public static final String EXPIRE = "expire";
  
  @SerializedName("amount")
  private Integer amount = null;

  @SerializedName("reciprocate")
  private Boolean reciprocate = false;

  @SerializedName("description")
  private String description = null;

  public CouponUserTransactionRequest amount(Integer amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * minimum: 0
   * @return amount
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getAmount() {
    return amount;
  }

  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  public CouponUserTransactionRequest reciprocate(Boolean reciprocate) {
    this.reciprocate = reciprocate;
    return this;
  }

   /**
   * Get reciprocate
   * @return reciprocate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getReciprocate() {
    return reciprocate;
  }

  public void setReciprocate(Boolean reciprocate) {
    this.reciprocate = reciprocate;
  }

  public CouponUserTransactionRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponUserTransactionRequest couponUserTransactionRequest = (CouponUserTransactionRequest) o;
    return Objects.equals(this.amount, couponUserTransactionRequest.amount) &&
        Objects.equals(this.reciprocate, couponUserTransactionRequest.reciprocate) &&
        Objects.equals(this.description, couponUserTransactionRequest.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, reciprocate, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponUserTransactionRequest {\n");

    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    reciprocate: ").append(toIndentedString(reciprocate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
