/*
 * Reffueld API
 * **Reffueld's API** 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.reffueld.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * CouponUser object returned as a response
 */
@ApiModel(description = "CouponUser object returned as a response")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T18:05:40.872Z")
public class CouponUserResponse {
  @SerializedName("id")
  private String id = null;

  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("created")
  private DateTime created = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("external_id")
  private String externalId = null;

  @SerializedName("role")
  private String role = null;

  @SerializedName("tags")
  private List<String> tags = new ArrayList<String>();

  @SerializedName("balance")
  private Integer balance = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("coupon_count")
  private Integer couponCount = null;

  @SerializedName("last_claim")
  private DateTime lastClaim = null;

  @SerializedName("last_transaction")
  private DateTime lastTransaction = null;

  public CouponUserResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * unique
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "unique")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CouponUserResponse enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public CouponUserResponse created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public CouponUserResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CouponUserResponse email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public CouponUserResponse externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public CouponUserResponse role(String role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public CouponUserResponse tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public CouponUserResponse addTagsItem(String tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public CouponUserResponse balance(Integer balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBalance() {
    return balance;
  }

  public void setBalance(Integer balance) {
    this.balance = balance;
  }

  public CouponUserResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CouponUserResponse couponCount(Integer couponCount) {
    this.couponCount = couponCount;
    return this;
  }

   /**
   * Get couponCount
   * @return couponCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCouponCount() {
    return couponCount;
  }

  public void setCouponCount(Integer couponCount) {
    this.couponCount = couponCount;
  }

  public CouponUserResponse lastClaim(DateTime lastClaim) {
    this.lastClaim = lastClaim;
    return this;
  }

   /**
   * Get lastClaim
   * @return lastClaim
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getLastClaim() {
    return lastClaim;
  }

  public void setLastClaim(DateTime lastClaim) {
    this.lastClaim = lastClaim;
  }

  public CouponUserResponse lastTransaction(DateTime lastTransaction) {
    this.lastTransaction = lastTransaction;
    return this;
  }

   /**
   * Get lastTransaction
   * @return lastTransaction
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getLastTransaction() {
    return lastTransaction;
  }

  public void setLastTransaction(DateTime lastTransaction) {
    this.lastTransaction = lastTransaction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponUserResponse couponUserResponse = (CouponUserResponse) o;
    return Objects.equals(this.id, couponUserResponse.id) &&
        Objects.equals(this.enabled, couponUserResponse.enabled) &&
        Objects.equals(this.created, couponUserResponse.created) &&
        Objects.equals(this.name, couponUserResponse.name) &&
        Objects.equals(this.email, couponUserResponse.email) &&
        Objects.equals(this.externalId, couponUserResponse.externalId) &&
        Objects.equals(this.role, couponUserResponse.role) &&
        Objects.equals(this.tags, couponUserResponse.tags) &&
        Objects.equals(this.balance, couponUserResponse.balance) &&
        Objects.equals(this.description, couponUserResponse.description) &&
        Objects.equals(this.couponCount, couponUserResponse.couponCount) &&
        Objects.equals(this.lastClaim, couponUserResponse.lastClaim) &&
        Objects.equals(this.lastTransaction, couponUserResponse.lastTransaction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, enabled, created, name, email, externalId, role, tags, balance, description, couponCount, lastClaim, lastTransaction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponUserResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    couponCount: ").append(toIndentedString(couponCount)).append("\n");
    sb.append("    lastClaim: ").append(toIndentedString(lastClaim)).append("\n");
    sb.append("    lastTransaction: ").append(toIndentedString(lastTransaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

