/*
 * Reffueld API
 * **Reffueld's API** 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.reffueld.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CouponTypeIssueRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-08T18:05:40.872Z")
public class CouponTypeIssueRequest {
  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("value")
  private Integer value = null;

  @SerializedName("from_user_id")
  private String fromUserId = null;

  @SerializedName("to_user_id")
  private String toUserId = null;

  @SerializedName("description")
  private String description = null;

  public CouponTypeIssueRequest quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * minimum: 1
   * @return quantity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public CouponTypeIssueRequest code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public CouponTypeIssueRequest value(Integer value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * minimum: 0
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getValue() {
    return value;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public CouponTypeIssueRequest fromUserId(String fromUserId) {
    this.fromUserId = fromUserId;
    return this;
  }

   /**
   * Get fromUserId
   * @return fromUserId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFromUserId() {
    return fromUserId;
  }

  public void setFromUserId(String fromUserId) {
    this.fromUserId = fromUserId;
  }

  public CouponTypeIssueRequest toUserId(String toUserId) {
    this.toUserId = toUserId;
    return this;
  }

   /**
   * Get toUserId
   * @return toUserId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getToUserId() {
    return toUserId;
  }

  public void setToUserId(String toUserId) {
    this.toUserId = toUserId;
  }

  public CouponTypeIssueRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponTypeIssueRequest couponTypeIssueRequest = (CouponTypeIssueRequest) o;
    return Objects.equals(this.quantity, couponTypeIssueRequest.quantity) &&
        Objects.equals(this.code, couponTypeIssueRequest.code) &&
        Objects.equals(this.value, couponTypeIssueRequest.value) &&
        Objects.equals(this.fromUserId, couponTypeIssueRequest.fromUserId) &&
        Objects.equals(this.toUserId, couponTypeIssueRequest.toUserId) &&
        Objects.equals(this.description, couponTypeIssueRequest.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantity, code, value, fromUserId, toUserId, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponTypeIssueRequest {\n");
    
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    fromUserId: ").append(toIndentedString(fromUserId)).append("\n");
    sb.append("    toUserId: ").append(toIndentedString(toUserId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

